# Generated by Django 4.2.25 on 2025-10-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='featured',
            new_name='is_featured',
        ),
    ]
