# Generated by Django 4.2.25 on 2025-10-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('avg_session_duration', models.FloatField(default=0.0, help_text='Average session duration in seconds')),
                ('blog_views', models.PositiveIntegerField(default=0)),
                ('project_views', models.PositiveIntegerField(default=0)),
                ('cv_views', models.PositiveIntegerField(default=0)),
                ('cv_downloads', models.PositiveIntegerField(default=0)),
                ('comments_submitted', models.PositiveIntegerField(default=0)),
                ('comments_approved', models.PositiveIntegerField(default=0)),
                ('top_blog_posts', models.JSONField(blank=True, default=list)),
                ('top_projects', models.JSONField(blank=True, default=list)),
                ('top_referrers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('referrer_url', models.URLField(blank=True, null=True)),
                ('referrer_domain', models.CharField(blank=True, max_length=255)),
                ('landing_page', models.CharField(max_length=500)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_visit'],
                'indexes': [models.Index(fields=['session_key'], name='analytics_v_session_67c61f_idx'), models.Index(fields=['-first_visit'], name='analytics_v_first_v_35f929_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('clicked_result', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='analytics.visitor')),
            ],
            options={
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('time_on_page', models.PositiveIntegerField(default=0, help_text='Time spent on page in seconds')),
                ('is_bounce', models.BooleanField(default=False)),
                ('exit_page', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.visitor')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['path', '-timestamp'], name='analytics_p_path_89b690_idx'), models.Index(fields=['content_type', 'object_id'], name='analytics_p_content_73920a_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('download', 'File Download'), ('external_link', 'External Link Click'), ('social_share', 'Social Share'), ('contact_form', 'Contact Form Submission'), ('search', 'Search Query'), ('cv_download', 'CV Download'), ('github_click', 'GitHub Link Click'), ('demo_click', 'Demo Link Click')], max_length=50)),
                ('event_category', models.CharField(max_length=100)),
                ('event_action', models.CharField(max_length=100)),
                ('event_label', models.CharField(blank=True, max_length=200)),
                ('event_value', models.CharField(blank=True, max_length=200)),
                ('page_url', models.CharField(max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.visitor')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', '-timestamp'], name='analytics_e_event_t_83e2d8_idx')],
            },
        ),
    ]
