# Generated by Django 4.2.25 on 2025-10-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectUpdate',
        ),
    ]
