# Generated by Django 4.2.25 on 2025-10-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text="Icon for category display (e.g., '⚛️', '🔧', 'FE', 'BE', or Font Awesome class)", max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order within category'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(help_text="Category name (e.g., 'Frontend', 'Backend', 'Cloud & DevOps', 'Tools')", max_length=100),
        ),
    ]
