name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        cd frontend
        npm install
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
